#!/usr/bin/env python3
"""Evaluate trained model on pre-cut test tiles.

Runs inference on individual 256x256 tiles (already generated by the
pipeline), compares predictions against weak labels, and reports
per-class metrics. Uses ~2 GB RAM, runs ~10 min on V100.

Usage:
    python research_paper/evaluate_tiles.py \
        --model-path research_paper/best_model.pth \
        --tiles-dir /path/to/wetlands_testdata/tiles \
        --output-dir /path/to/wetlands_testdata/results
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
import segmentation_models_pytorch as smp
from torch.utils.data import DataLoader, Dataset
import rasterio


class TileDataset(Dataset):
    """Loads image/label tile pairs from the pipeline's tiles directory."""

    def __init__(self, tiles_dir: Path, in_channels: int = 10):
        self.in_channels = in_channels
        self.image_dir = tiles_dir / "images"
        self.label_dir = tiles_dir / "labels"

        self.image_files = sorted(self.image_dir.glob("*.tif"))
        if not self.image_files:
            raise FileNotFoundError(f"No .tif files in {self.image_dir}")

        self.label_files = []
        for img_f in self.image_files:
            lbl_f = self.label_dir / img_f.name
            if lbl_f.exists():
                self.label_files.append(lbl_f)
            else:
                self.label_files.append(None)

    def __len__(self) -> int:
        return len(self.image_files)

    def __getitem__(self, idx: int):
        with rasterio.open(self.image_files[idx]) as src:
            image = src.read().astype(np.float32)

        if image.shape[0] > self.in_channels:
            image = image[: self.in_channels]
        elif image.shape[0] < self.in_channels:
            pad = np.zeros(
                (self.in_channels - image.shape[0], image.shape[1], image.shape[2]),
                dtype=np.float32,
            )
            image = np.concatenate([image, pad], axis=0)

        label = np.full(
            (image.shape[1], image.shape[2]), -1, dtype=np.int64
        )
        if self.label_files[idx] is not None:
            with rasterio.open(self.label_files[idx]) as src:
                label = src.read(1).astype(np.int64)

        return torch.from_numpy(image), torch.from_numpy(label)


def evaluate(
    model_path: str,
    tiles_dir: str,
    output_dir: str,
    architecture: str = "unetplusplus",
    encoder_name: str = "resnet50",
    in_channels: int = 10,
    num_classes: int = 4,
    batch_size: int = 32,
    num_workers: int = 4,
) -> dict:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}", flush=True)

    model = smp.create_model(
        architecture,
        encoder_name=encoder_name,
        encoder_weights=None,
        in_channels=in_channels,
        classes=num_classes,
    )
    state_dict = torch.load(model_path, map_location=device, weights_only=True)
    model.load_state_dict(state_dict)
    model.to(device)
    model.eval()

    dataset = TileDataset(Path(tiles_dir), in_channels=in_channels)
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )

    print(
        f"Evaluating {len(dataset)} tiles, {len(loader)} batches "
        f"(bs={batch_size})",
        flush=True,
    )

    conf = torch.zeros(num_classes, num_classes, dtype=torch.long)
    t0 = time.time()

    with torch.no_grad():
        for batch_i, (images, labels) in enumerate(loader):
            images = images.to(device)
            logits = model(images)
            preds = logits.argmax(dim=1).cpu()

            valid = labels >= 0
            if not valid.any():
                continue

            t_flat = labels[valid].to(torch.int64).clamp_(0, num_classes - 1)
            p_flat = preds[valid].to(torch.int64).clamp_(0, num_classes - 1)
            idx = t_flat * num_classes + p_flat
            conf += torch.bincount(
                idx, minlength=num_classes * num_classes
            ).view(num_classes, num_classes)

            if (batch_i + 1) % 20 == 0 or batch_i == len(loader) - 1:
                elapsed = time.time() - t0
                print(
                    f"  Batch {batch_i+1}/{len(loader)} [{elapsed:.0f}s]",
                    flush=True,
                )

    elapsed = time.time() - t0
    print(f"\nInference done in {elapsed:.0f}s", flush=True)

    conf_np = conf.numpy()
    total_pixels = conf_np.sum()
    overall_acc = float(np.trace(conf_np)) / float(total_pixels) if total_pixels > 0 else 0.0

    class_names = {0: "upland", 1: "emergent", 2: "forested", 3: "pond"}
    per_class = {}
    ious = []

    for c in range(num_classes):
        tp = conf_np[c, c]
        fp = conf_np[:, c].sum() - tp
        fn = conf_np[c, :].sum() - tp
        iou = float(tp) / float(tp + fp + fn) if (tp + fp + fn) > 0 else 0.0
        precision = float(tp) / float(tp + fp) if (tp + fp) > 0 else 0.0
        recall = float(tp) / float(tp + fn) if (tp + fn) > 0 else 0.0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
        name = class_names.get(c, f"class_{c}")
        per_class[name] = {
            "iou": round(iou, 4),
            "f1": round(f1, 4),
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "support": int(conf_np[c, :].sum()),
        }
        ious.append(iou)

    results = {
        "overall_accuracy": round(overall_acc, 4),
        "mean_iou": round(float(np.mean(ious)), 4),
        "per_class": per_class,
        "confusion_matrix": conf_np.tolist(),
        "total_pixels": int(total_pixels),
        "num_tiles": len(dataset),
        "inference_time_s": round(elapsed, 1),
    }

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    metrics_file = out_path / "test_metrics.json"
    with open(metrics_file, "w") as f:
        json.dump(results, f, indent=2)

    print(f"\n{'='*50}")
    print(f"Overall Accuracy: {results['overall_accuracy']:.4f}")
    print(f"Mean IoU:         {results['mean_iou']:.4f}")
    print(f"{'='*50}")
    for name, m in per_class.items():
        print(f"  {name:12s}  IoU={m['iou']:.4f}  F1={m['f1']:.4f}  "
              f"P={m['precision']:.4f}  R={m['recall']:.4f}  "
              f"support={m['support']:,}")
    print(f"{'='*50}")
    print(f"Saved: {metrics_file}", flush=True)

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate model on test tiles")
    parser.add_argument("--model-path", required=True)
    parser.add_argument("--tiles-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--architecture", default="unetplusplus")
    parser.add_argument("--encoder-name", default="resnet50")
    parser.add_argument("--in-channels", type=int, default=10)
    parser.add_argument("--num-classes", type=int, default=4)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--num-workers", type=int, default=4)
    args = parser.parse_args()

    evaluate(
        model_path=args.model_path,
        tiles_dir=args.tiles_dir,
        output_dir=args.output_dir,
        architecture=args.architecture,
        encoder_name=args.encoder_name,
        in_channels=args.in_channels,
        num_classes=args.num_classes,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
    )
